#!/bin/sh

for repo in unstable testing stable raring saucy cloudprintppa ; do
    for pkg in cloudprint cloudprint-service ; do
        reprepro -Vb . --ignore=wrongdistribution includedeb $repo ../../$pkg\_*_all.deb
    done
done

rm -rf db/

rm -f dists/sid
ln -s ./unstable dists/sid
rm -f dists/jessie
ln -s ./testing dists/jessie
rm -f dists/wheezy
ln -s ./stable dists/wheezy
