.\" (C) Copyright 2013-2015 David Steele <dsteele@gmail.com>,
.\"
.\" This file is part of cloudprint
.\" Available under the terms of the GNU General Public License version 2 or later
.TH CLOUDPRINT-SERVICE 7 2015-05-31 Linux "System Commands"
.SH NAME
cloudprint-service \- manage the Google Cloud Print proxy

.SH SYNOPSIS
.TP
systemctl \fIstart\fR \fBcloudprintd.service\fR
Start the \fBcloudprintd\fR service. This will fail if the credentials have not been
established. The service will normally start automatically when the computer
is running.
.TP
systemctl \fIstop\fR \fBcloudprintd.service\fR
Stop the \fBcloudprintd\fR service. Login credentials are not lost. Normally,
the printer will continue to be shown as a valid destination. Any jobs spooled
during that time will print when the service is restarted.
.TP
systemctl \fIstatus\fR \fBcloudprintd.service\fR
Determine whether the service is running or not.

.SH DESCRIPTION
The \fBcloudprintd\fR services manages the operation of a Google Cloud Print
proxy. It makes locally-defined CUPS printers available for use by approved
Google users, both locally and remotely.

Authentication credentials can be established using the wrapper script
\fBcps-auth\fR.
.SH FILES
.TP
\fI/etc/default/cloudprintd\fR
This file contains a number of parameters that control cloudprint.
View the file for more details.
.TP
\fI/etc/cloudprint.conf\fR, \fI~/.cloudprint.conf\fR
Can contain additional command line parameters for \fBcloudprint\fR.

.SH SEE ALSO
.BR cloudprint(1), cps-auth(1)
