#!/bin/bash

GUSER=$1
AUTHTEMP=/tmp/authtemp

if [ ! -n "$1" ] ; then
    echo "Usage: $0 <google user name>";
    exit -1;
fi

cloudprint-auth $GUSER -o $AUTHTEMP

sudo cp $AUTHTEMP /var/lib/cloudprintd/authfile

rm -f $AUTHTEMP

